adding changes to the jobCard
mindlab-vojo/vojo-component-library pull request #121
Opened 2021-06-14 18:19 UTC by DiaMont30

2021-06-14 18:51 UTC, meltammy requested changes

2021-06-14 18:51 UTC, meltammy commented on src/components/JobCard/JobCard.js
>        return locations[0].states.map(state => (
Poderia manter como estava e adicionar apenas um novo array a ser mapeado:
```
const newStates = locations[0].states.length > 4
        ? [...locations[0].states.slice(0, 4), `+ ${locations[0].states.slice(4).length}`]
        : locations[0].states
```

2021-06-14 18:53 UTC, meltammy commented on src/components/JobCard/JobCard.js
>        return locations[0].states.map(state => (
Ficaria assim:
``` javascript
 else if (states) {
      const newStates = locations[0].states.length > 4
        ? [...locations[0].states.slice(0, 4), `+ ${locations[0].states.slice(4).length}`]
        : locations[0].states
      return newStates.map(state => (
        <JobCard.LocationCircle
          key={state}
          theme={theme}>
          <Typography
            type={'label'}
            fontWeight="bolder"
            color={theme.colors.primaryColor}

          >
            {state}
          </Typography>
        </JobCard.LocationCircle>
      ))
    }
```

2021-06-14 21:46 UTC, ricardo-rp commented
LGTM

2021-06-14 21:47 UTC, ricardo-rp approved these changes

2021-06-15 14:08 UTC, meltammy approved these changes
LGTM

2021-06-15 14:08 UTC, merged